settings:
  title: '状态检查'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: https://cdn.jsdelivr.net/gh/wayne0926/wayne0926/favicon.ico # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有的系统都在运作'
  notAllmonitorsOperational: '并非所有的系统都在运作'
  monitorLabelOperational: '运作'
  monitorLabelNotOperational: '没有运作'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切完好'
  dayInHistogramNotOperational: ' 事件' # xx incident(s) recorded

monitors:
  - id: wr0926-ml # unique identifier
    name: Wr0926.Ml
    description: '时过境迁Wayne博客' # default=empty
    url: 'https://wr0926.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: '专为连接到Internet的任何内容而构建。'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200

  - id: github-com
    name: GitHub
    url: 'https://github.com/'
    method: GET
    expectStatus: 200
    
  - id: oauth
    name: 网站评论系统
    url: 'https://oauth.wr0926.ml'
    method: GET
    expectStatus: 200
  
  - id: euserv
    name: euserv
    url: 'https://admin.wr0926.ga'
    method: GET
    expectStatus: 200
    followRedirect: true # should fetch follow redirects, default=false

  - id: kod
    name: 可道云
    url: 'https://kod.wr0926.ml'
    method: GET
    expectStatus: 200
    
  - id: v2-u1
    name: v2u1
    url: 'http://tp.wr0926.ga'
    method: GET
    expectStatus: 404

  - id: cr
    name: 云
    url: 'https://cr.wr0926.ml'
    method: GET
    expectStatus: 200
